# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session_replay.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_source_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_source_button.setObjectName("load_source_button")
        self.verticalLayout_2.addWidget(self.load_source_button)
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setEnabled(False)
        self.run_button.setObjectName("run_button")
        self.verticalLayout_2.addWidget(self.run_button)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.requests_table_widget = QtWidgets.QTableWidget(self.centralwidget)
        self.requests_table_widget.setColumnCount(0)
        self.requests_table_widget.setObjectName("requests_table_widget")
        self.requests_table_widget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.requests_table_widget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 31))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.settings = QtWidgets.QAction(MainWindow)
        self.settings.setObjectName("settings")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.load_file_action = QtWidgets.QAction(MainWindow)
        self.load_file_action.setObjectName("load_file_action")
        self.menu.addAction(self.load_file_action)
        self.menu.addAction(self.settings)
        self.menu.addAction(self.about)
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fiddler Session Replay"))
        self.load_source_button.setText(_translate("MainWindow", "Choose File"))
        self.run_button.setText(_translate("MainWindow", "Run Session"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.settings.setText(_translate("MainWindow", "Settings"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.about.setText(_translate("MainWindow", "About"))
        self.load_file_action.setText(_translate("MainWindow", "Load file"))
        self.load_file_action.setShortcut(_translate("MainWindow", "Ctrl+O"))
